include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
