name: colorbrewer
description: "ColorBrewer: color palettes optimized for data visualization."
homepage: https://github.com/albemala/brewer_colors
version: 1.0.2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
